export const dashboardStats = [
  { id: 'banks', title: 'عدد بنوك الأسئلة', value: 18, delta: '+3 هذا الشهر', tone: 'indigo' },
  { id: 'exams', title: 'عدد الاختبارات', value: 42, delta: '+8 هذا الشهر', tone: 'emerald' },
  { id: 'students', title: 'عدد الطلاب النشطين', value: 1240, delta: '+12%', tone: 'sky' },
]

export const recentActivities = [
  {
    id: 1,
    action: 'إنشاء اختبار جديد',
    target: 'فيزياء 101 - اختبار منتصف الفصل',
    actor: 'د. نورا أحمد',
    time: 'منذ 10 دقائق',
    status: 'تم النشر',
  },
  {
    id: 2,
    action: 'تحديث بنك أسئلة',
    target: 'أساسيات الجبر',
    actor: 'أ. سمير عادل',
    time: 'منذ ساعة',
    status: 'تم التحديث',
  },
  {
    id: 3,
    action: 'الموافقة على طلب صلاحية',
    target: 'بنك الأحياء المشترك',
    actor: 'د. رانيا يوسف',
    time: 'منذ 3 ساعات',
    status: 'مقبول',
  },
  {
    id: 4,
    action: 'إضافة طلاب إلى المقرر',
    target: 'شبكات الحاسوب',
    actor: 'م. عمر خالد',
    time: 'اليوم 08:20 ص',
    status: 'مكتمل',
  },
  {
    id: 5,
    action: 'جدولة اختبار نهائي',
    target: 'برمجة كائنية التوجه',
    actor: 'د. هبة علي',
    time: 'اليوم 10:45 ص',
    status: 'قيد المراجعة',
  },
  {
    id: 6,
    action: 'حذف سؤال مكرر',
    target: 'بنك الرياضيات المتقدمة',
    actor: 'أ. مازن فارس',
    time: 'أمس 06:10 م',
    status: 'تم التنفيذ',
  },
  {
    id: 7,
    action: 'تعديل وقت الاختبار',
    target: 'هندسة البرمجيات - الشعبة B',
    actor: 'د. سارة مصطفى',
    time: 'أمس 03:35 م',
    status: 'تم التعديل',
  },
  {
    id: 8,
    action: 'إرسال تنبيه للطلاب',
    target: 'اختبار قواعد البيانات',
    actor: 'م. كريم عبد الله',
    time: 'قبل يومين',
    status: 'تم الإرسال',
  },
  {
    id: 9,
    action: 'أرشفة اختبار قديم',
    target: 'مقدمة في الإحصاء',
    actor: 'د. ليلى حسن',
    time: 'قبل 3 أيام',
    status: 'مؤرشف',
  },
  {
    id: 10,
    action: 'نسخ بنك أسئلة',
    target: 'كيمياء عامة - نسخة الفصل الجديد',
    actor: 'أ. طارق جابر',
    time: 'قبل 4 أيام',
    status: 'تم النسخ',
  },
]
